### ISSUE TITLE
disallow duplicate folder names at the same level

### ISSUE THREAD

**Issue by grahamu** [pinax/pinax-documents#14]
Just a thought... perhaps we should not allow duplicate folder names at the same inheritance level.
By this I mean all non-child Folders must have unique names, and child Folders with the same parent must have unique names.

**Comment by paltman** [comment]
:+1: 

I'd also be for making file names unique within a directory to further map to files in a filesystem.  Thoughts @brosner?

**Comment by ethankent** [comment]
I also agree. I think that folder names should be unique amongst their siblings. They really must support a sort of URI functionality, so that /a/perfect/path/ only resolves to one location in a domain. I'd also say that document names should probably be unique amongst their siblings for the same reason.

I'd be happy to take a look at this.

**Comment by paltman** [comment]
@ethankent that would be great if you could, at this point, i think we are might have to punt on this feature for 16.04, which i hate because now that I think about it, it could prove problematic for people that are running the next released version and they have duplicate names.  For this reason, I'm inclined to say we make an exception to the cut off of today for app releases, if we can managed to get something done in the next several days and shipped in a starter project.

**Comment by paltman** [comment]
@ethankent i might actually take a stab at this right now
