### ISSUE TITLE
How to run this project 

### ISSUE THREAD

**Issue by snaveen1856** [pinax/pinax-documents#31]
**Ask a question**
A clear and concise description of what the question is. 

Can anyone tell, how to run this project with command? I hope this is web application

**Comment by KatherineMichel** [comment]
@snaveen1856 Hello... it's a Django app that can be included in a Django project. There are pinax-starter-apps that already include Pinax apps. Or, you can install and integrate the Pinax app in the project, like normal.

**Comment by nithee123** [comment]
@KatherineMichel Can you please provide detailed answer. I'm just learning python and django.. how we can run this project just like any other django web application.

**Comment by KatherineMichel** [comment]
@nithee123 What is in this repo is not actually a project, it's an app that can be included in a Django project. The way that Pinax works is that you either use a Pinax Starter Project, which already contains Pinax apps, or you install a Pinax app in an existing project. I will warn you that because we are still finishing up a new release, there are some updates that have not yet been made to Pinax Starter Projects... but if you are interested in using one, the usual process is to install Pinax CLI, then use it to install a Pinax Starter Project, which will already have some apps included. Here are a couple of docs links below:

Here are instructions for starting a project using a Pinax Starter Project: https://pinaxproject.com/pinax/quick_start/

The general instructions to install pinax-documents in an existing project can be found in this repo's README: https://github.com/pinax/pinax-documents#installation

**Comment by KatherineMichel** [comment]
Closing issue. Let me know if you have any other questions.

**Comment by nithee123** [comment]
Thanks Katherine.. it helps to understand the project better
